version: 2

sources:
  - name: my_source
    database: demo
    schema: DEMO_SCHEMA
    tables:
      - name: bike
      - name: weather
      
  - name: us_crime
    database: US_CRIME
    schema: CYBERSYN
    tables:
      - name: urban_crime_incident_log


