WITH TRIPS as (

select
RIDE_ID,
-- RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(START_AT)) AS TRIP_DATE,
START_STATION_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CASUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND,TO_TIMESTAMP(START_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS

from {{ source('my_source', 'bike') }}

where RIDE_ID != '"bikeid"' and RIDE_ID != 'bikeid'



)

select
*
from TRIPS